import streamlit as st
from logics.customer_query_handler import process_user_message

st.set_page_config(
    layout="centered",
    page_title="My Streamlit App"
)

st.title("Streamlit App")

form = st.form(key="form")
form.subheader("Prompt")
user_prompt = form.text_area("Enter your prompt here", height=200)

if form.form_submit_button("Submit"):
    st.toast(f"User Input Submitted - {user_prompt}")
    
    # Unpack the two returned objects
    response, matched_courses = process_user_message(user_prompt)
    
    # 1. Output the text explanation generated by the LLM
    st.write(response)
    
    # 2. Display specific data structures if relevant records exist
    if matched_courses:
        st.write("---")
        st.markdown("### 🏆 Recommended Course Details")
        
        for course in matched_courses:
            if course: # Ensure item is not None
                with st.expander(f"📚 {course.get('course_name', 'Unknown Course')}", expanded=True):
                    col1, col2, col3 = st.columns(3)
                    with col1:
                        st.metric(label="Price", value=course.get('price', 'N/A'))
                    with col2:
                        st.metric(label="Rating", value=course.get('rating', 'N/A'))
                    with col3:
                        st.metric(label="Duration", value=course.get('duration', 'N/A'))
                    
                    st.write(f"**Description:** {course.get('description', 'No description details provided.')}")
                    
                    skills = course.get('skills_covered', [])
                    if skills:
                        st.write(f"**Skills to Learn:** {', '.join(skills)}")